name: Code Analysis

on:
  push:
    branches:
      - master

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SonarQube Scan
      run: |
        sonar-scanner -Dsonar.projectKey=my_project
